const tabLabels = [
  "Our Old Clients",
  "Our Permanant Clients",
  "Our New Client",
  "Our Total Clients",
];

const clientsOptions = ["Delhi Clients", "Mumbai Clients", "Pune Clients"];
const clientAddDuration = ["Today", "This Week", "This Month"];

const tableColumns = [
  "PO. DATE",
  "Id.NO.",
  "PO. NAME",
  "Email",
  "Address",
  "CONTACT N0.",
  "Company Name",
  "Company Type",
  "STATUS",
];

const mackRows = [
  {
    date: "2024-05-05",
    no: "10001",
    name: "vishal due",
    email: "jonh123@gmail.com",
    address: "Delhi Branch",
    contact: "9876543210",
    company: "info...",
    type: "mnc",
    status: "done",
  },
  {
    date: "2025-07-09",
    no: "10002",
    name: "navesh Patil",
    email: "shrikant12@gmail.com",
    address: "mumbai Branch",
    contact: "975392722",
    company: "vipro",
    type: "MNC",
    status: "done",
  },
  {
    date: "2025-05-08",
    no: "10003",
    name: "shrikant Patil",
    email: "shrikant12@gmail.com",
    address: "mumbai Branch",
    contact: "975392722",
    company: "vipro",
    type: "MNC",
    status: "done",
  },
  {
    date: "2021-10-04",
    no: "10004",
    name: "shrikant Patil",
    email: "shrikant12@gmail.com",
    address: "mumbai Branch",
    contact: "975392722",
    company: "vipro",
    type: "MNC",
    status: "done",
  },
  {
    date: "2024-11-12",
    no: "10005",
    name: "shrikant Patil",
    email: "shrikant12@gmail.com",
    address: "mumbai Branch",
    contact: "975392722",
    company: "vipro",
    type: "MNC",
    status: "done",
  },
  {
    date: "2025-01-02",
    no: "10006",
    name: "shrikant Patil",
    email: "shrikant12@gmail.com",
    address: "mumbai Branch",
    contact: "975392722",
    company: "vipro",
    type: "MNC",
    status: "done",
  },
  {
    date: "2025-01-02",
    no: "10006",
    name: "shrikant Patil",
    email: "shrikant12@gmail.com",
    address: "mumbai Branch",
    contact: "975392722",
    company: "vipro",
    type: "MNC",
    status: "done",
  },
  {
    date: "2022-02-03",
    no: "10008",
    name: "shrikant Patil",
    email: "shrikant12@gmail.com",
    address: "mumbai Branch",
    contact: "975392722",
    company: "vipro",
    type: "MNC",
    status: "done",
  },
];